spring:
  jpa:
    hibernate:
      # Ustawienie validate oznacza, że podczas uruchamiania aplikacji Spring Hibernate sprawdza, czy struktura tabel
      # w bazie danych jest zgodna z definicjami encji (klas oznaczonych jako @Entity).
      # Jeśli coś się nie zgadza (np. brak kolumny w tabeli), aplikacja nie uruchomi się.
      ddl-auto: validate